[package]
name = "appflowy-cloud-billing-client"
version = "0.1.0"
edition = "2021"

[dependencies]
client-api = "0.1.0"
reqwest = "0.11"
serde = "1.0"
serde_json = "1.0"
tokio = "1.37"
shared-entity = { git = "https://github.com/AppFlowy-IO/AppFlowy-Cloud", rev = "48281f43e5ccd374c30888c1d26e9716d1da6541" }

[patch.crates-io]
# will be removed when using yrs 0.18.2 that expose pendings
# yrs = { git = "https://github.com/appflowy/y-crdt", rev = "3f25bb510ca5274e7657d3713fbed41fb46b4487" }
client-api = { git = " https://github.com/AppFlowy-IO/AppFlowy-Cloud", rev = "48281f43e5ccd374c30888c1d26e9716d1da6541" }
collab = { git = "https://github.com/AppFlowy-IO/AppFlowy-Collab", rev = "870cd70" }
collab-entity = { git = "https://github.com/AppFlowy-IO/AppFlowy-Collab", rev = "870cd70" }
collab-document = { git = "https://github.com/AppFlowy-IO/AppFlowy-Collab", rev = "870cd70" }
collab-folder = { git = "https://github.com/AppFlowy-IO/AppFlowy-Collab", rev = "870cd70" }

[dev-dependencies]
# AppFlowy dependencies
client-api-test-util = { git = "https://github.com/AppFlowy-IO/AppFlowy-Cloud", rev = "48281f43e5ccd374c30888c1d26e9716d1da6541" }
